### ISSUE TITLE
win the game on first turn

### ISSUE THREAD

**Issue by martintseng** [laihaotao/COMP354#24]
The player wins immediately when you click on End Turn.
It probably checks the winning conditions directly without giving the AI a chance to play any pokemon cards

**Comment by FredericDesgreniers** [comment]
I commented out the checkWinLose() function since it's the one causing the game to quit. It should be fixed before next release so we have more than one win condition.

Prize cards are already checked whenever one is given out, as seen on gameboard, line 212, so it's probablyunnecessary to check for it in the checkWinLose() method

**Comment by laihaotao** [comment]
disable `checkWinLose()` method in the first turn, fixed, close.
