### ISSUE TITLE
Attack cancel cannot perform

### ISSUE THREAD

**Issue by laihaotao** [laihaotao/COMP354#30]
When you click the pokemon ability, and the window pop up. if you click the cancel button, the system will think do an attack and when you click the ability again, nothing will happen.

**Comment by FredericDesgreniers** [comment]
The way I changed is that if the ability does something, it counts as used, however, if none of the ability parts are used, it returns as not used and does not trigger the limit.

This means it will trigger as used if only 1 of the parts work, so this will need to be changed later so that failing any part of the ability cancels the whole ability. 

For example, an ability with only damage to a choice will not count as used when pressing cancel, however, an ability with flat damage to active + damage to choice will count as used even if the choice is cancelled, since the flat damage has already been applied.
